name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolset: gcc
            compiler: g++
          - os: ubuntu-latest
            toolset: clang
            compiler: clang++
          - os: windows-latest
            toolset: msvc
            compiler: cl.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checking out dependencies
        working-directory: ../
        run: |
          git clone https://github.com/boostorg/boost.git
          git clone https://gitlab.com/libeigen/eigen.git
      - name: Boost installation 1
        working-directory: ../boost
        run: |
          git submodule update --init tools/build
          git submodule update --init libs/config
          git submodule update --init tools/boostdep
          git submodule update --init tools/boost_install
          git submodule update --init libs/headers
      - name: Boost installation 2 (POSIX)
        if: runner.os != 'Windows'
        working-directory: ../boost
        run: |
          mkdir -p libs/numeric/odeint
          cp -r $GITHUB_WORKSPACE/* libs/numeric/odeint
          python3 tools/boostdep/depinst/depinst.py numeric/odeint
          ./bootstrap.sh
          ./b2 headers
          echo "using ${{ matrix.toolset }} : : ${{ matrix.compiler }} ;" >user-config.jam
      - name: Boost installation 3 (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        working-directory: ../boost
        run: |
          New-Item libs/numeric/odeint -ItemType Directory -ErrorAction SilentlyContinue
          Get-ChildItem -Path $env:GITHUB_WORKSPACE | ForEach-Object { Copy-Item -Recurse $env:GITHUB_WORKSPACE/$_ libs/numeric/odeint }
          python tools/boostdep/depinst/depinst.py numeric/odeint
          ./bootstrap.bat
          ./b2 headers
          echo "using ${{ matrix.toolset }} : : ${{ matrix.compiler }} ;" | Out-File user-config.jam
      - name: Test
        env:
          BOOST_ROOT: ${{ github.workspace }}/../boost
          EIGEN_ROOT: ${{ github.workspace }}/../eigen
        working-directory: ../boost
        run: |
          ./b2 -j 4 libs/numeric/odeint libs/numeric/odeint/test_external/eigen toolset=${{ matrix.toolset }}
